name: urlzap
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Generate & Deploy
    steps:
    # Checkout your repo locally
    - uses: actions/checkout@v2

    # Generate files using this action
    - name: Generate static site with urlzap
      uses: brunoluiz/urlzap-github-action@v1
      with:
        config: ./links.yaml

    # Deploy in Github Pages (you can use others)
    # also exclude the README.md file
    - name: deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: .
